name: Testing

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 18
      - name: Install Dependencies for the test file
        run: npm ci
        working-directory: ./test
      - name: Install Main dependencies for the package
        run: npm ci
      - name: Start Testing
        run: npm run test
        env:
          CI: true
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
